In [2]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\megha\appdata\roaming\python\python312\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\megha\appdata\roaming\python\python312\site-packages (from pandas) (2.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\megha\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\megha\appdata\roaming\python\python312\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\megha\appdata\roaming\python\python312\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\megha\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [3]:
import pandas as pd

In [6]:
movies=pd.read_csv('top10K-TMDB-movies.csv/top10K-TMDB-movies.csv')

In [8]:
movies.head()

,id,original_language,original_title,overview,popularity,release_date,title,vote_average,vote_count
0,851644,ko,20세기 소녀,Yeon-du asks her best friend Bora to collect a...,170.540,2022-10-06,20th Century Girl,8.7,290
1,238,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",86.518,1972-03-14,The Godfather,8.7,16988
2,278,en,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,84.681,1994-09-23,The Shawshank Redemption,8.7,22748
3,240,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,44.957,1974-12-20,The Godfather Part II,8.6,10293
4,667257,es,Cosas imposibles,"Matilde is a woman who, after the death of her...",32.859,2021-06-17,Impossible Things,8.6,299

In [7]:
movies.describe()

                  id    popularity  vote_average    vote_count
count   10000.000000  10000.000000  10000.000000  10000.000000
mean   161243.505000     34.697267      6.621150   1547.309400
std    211422.046043    211.684175      0.766231   2648.295789
min         5.000000      0.600000      4.600000    200.000000
25%     10127.750000      9.154750      6.100000    315.000000
50%     30002.500000     13.637500      6.600000    583.500000
75%    310133.500000     25.651250      7.200000   1460.000000
max    934761.000000  10436.917000      8.700000  31917.000000

In [8]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 10000 non-null  int64
 1   title              10000 non-null  object
 2   genre              9997 non-null   object
 3   original_language  10000 non-null  object
 4   overview           9987 non-null   object
 5   popularity         10000 non-null  float64
 6   release_date       10000 non-null  object
 7   vote_average       10000 non-null  float64
 8   vote_count         10000 non-null  int64
dtypes: float64(2), int64(2), object(5)
memory usage: 703.3+ KB

In [9]:
movies.isnull().sum()

id                    0
title                 0
genre                 3
original_language     0
overview             13
popularity            0
release_date          0
vote_average          0
vote_count            0
dtype: int64

In [12]:
movies.columns

Index(['id', 'original_language', 'original_title', 'overview', 'popularity',
       'release_date', 'title', 'vote_average', 'vote_count'],
      dtype='object')

In [37]:
movies_modified=movies[['id', 'title', 'overview', 'genre']]

In [38]:
movies_modified

,id,title,overview,genre
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,"Drama,Crime"
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...","Comedy,Drama,Romance"
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","Drama,Crime"
3,424,Schindler's List,The true story of how businessman Oskar Schind...,"Drama,History,War"
4,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...,"Drama,Crime"
...,...,...,...,...
9995,10196,The Last Airbender,"The story follows the adventures of Aang, a yo...","Action,Adventure,Fantasy"
9996,331446,Sharknado 3: Oh Hell No!,The sharks take bite out of the East Coast whe...,"Action,TV Movie,Science Fiction,Comedy,Adventure"
9997,13995,Captain America,"During World War II, a brave, patriotic Americ...","Action,Science Fiction,War"
9998,2312,In the Name of the King: A Dungeon Siege Tale,A man named Farmer sets out to rescue his kidn...,"Adventure,Fantasy,Action,Drama"
9999,455957,Domino,Seeking justice for his partner’s murder by an...,"Thriller,Action,Crime"

In [39]:
movies_modified['tags'] = movies_modified['overview']+movies_modified['genre']

In [40]:
movies_modified

,id,title,overview,genre,tags
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,"Drama,Crime",Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...","Comedy,Drama,Romance","Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","Drama,Crime","Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,The true story of how businessman Oskar Schind...,"Drama,History,War",The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...,"Drama,Crime",In the continuing saga of the Corleone crime f...
...,...,...,...,...,...
9995,10196,The Last Airbender,"The story follows the adventures of Aang, a yo...","Action,Adventure,Fantasy","The story follows the adventures of Aang, a yo..."
9996,331446,Sharknado 3: Oh Hell No!,The sharks take bite out of the East Coast whe...,"Action,TV Movie,Science Fiction,Comedy,Adventure",The sharks take bite out of the East Coast whe...
9997,13995,Captain America,"During World War II, a brave, patriotic Americ...","Action,Science Fiction,War","During World War II, a brave, patriotic Americ..."
9998,2312,In the Name of the King: A Dungeon Siege Tale,A man named Farmer sets out to rescue his kidn...,"Adventure,Fantasy,Action,Drama",A man named Farmer sets out to rescue his kidn...
9999,455957,Domino,Seeking justice for his partner’s murder by an...,"Thriller,Action,Crime",Seeking justice for his partner’s murder by an...

In [41]:
new_data  = movies_modified.drop(columns=['overview', 'genre'])

In [42]:
new_data

,id,title,tags
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...
...,...,...,...
9995,10196,The Last Airbender,"The story follows the adventures of Aang, a yo..."
9996,331446,Sharknado 3: Oh Hell No!,The sharks take bite out of the East Coast whe...
9997,13995,Captain America,"During World War II, a brave, patriotic Americ..."
9998,2312,In the Name of the King: A Dungeon Siege Tale,A man named Farmer sets out to rescue his kidn...
9999,455957,Domino,Seeking justice for his partner’s murder by an...

In [19]:
!pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Collecting scikit-learn
  Downloading scikit_learn-1.5.2-cp312-cp312-win_amd64.whl.metadata (13 kB)
Requirement already satisfied: numpy>=1.19.5 in c:\users\megha\appdata\roaming\python\python312\site-packages (from scikit-learn) (2.1.1)
Collecting scipy>=1.6.0 (from scikit-learn)
  Downloading scipy-1.14.1-cp312-cp312-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.2.0 (from scikit-learn)
  Downloading joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn)
  Downloading threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.5.2-cp312-cp312-win_amd64.whl (11.0 MB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.0 MB 1.1 MB/s eta 0:00:10
   --- ------------------------------------ 1.0/11.0 MB 1.5 MB/s eta 0:00:07
   ----- ---------------------------------- 1.6/11.0 MB 1.7 MB/s eta 0:00:06
   -------- ------------------------------- 2.4/11.0 MB 2.1 MB/s eta 0:00:05
   ----------- ---------------------------- 3.1/11.0 MB 2.3 MB/s eta 0:00:04
   ------------- -------------------------- 3.7/11.0 MB 2.3 MB/s eta 0:00:04
   --------------- ------------------------ 4.2/11.0 MB 2.4 MB/s eta 0:00:03
   ------------------ --------------------- 5.0/11.0 MB 2.5 MB/s eta 0:00:03
   -------------------- ------------------- 5.8/11.0 MB 2.7 MB/s eta 0:00:02
   ------------------------ --------------- 6.8/11.0 MB 2.9 MB/s eta 0:00:02
   --------------------------- ------------ 7.6/11.0 MB 3.0 MB/s eta 0:00:02
   ------------------------------ --------- 8.4/11.0 MB 3.0 MB/s eta 0:00:01
   --------------------------------- ------ 9.2/11.0 MB 3.1 MB/s eta 0:00:01
   ------------------------------------- -- 10.2/11.0 MB 3.2 MB/s eta 0:00:01
   ---------------------------------------  10.7/11.0 MB 3.3 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 3.1 MB/s eta 0:00:00
Downloading joblib-1.4.2-py3-none-any.whl (301 kB)
Downloading scipy-1.14.1-cp312-cp312-win_amd64.whl (44.5 MB)
   ---------------------------------------- 0.0/44.5 MB ? eta -:--:--
    --------------------------------------- 0.8/44.5 MB 3.4 MB/s eta 0:00:14
   - -------------------------------------- 1.6/44.5 MB 3.7 MB/s eta 0:00:12
   -- ------------------------------------- 2.4/44.5 MB 3.6 MB/s eta 0:00:12
   -- ------------------------------------- 2.6/44.5 MB 3.6 MB/s eta 0:00:12
   --- ------------------------------------ 3.4/44.5 MB 3.4 MB/s eta 0:00:13
   --- ------------------------------------ 3.9/44.5 MB 3.2 MB/s eta 0:00:13
   ---- ----------------------------------- 4.5/44.5 MB 3.2 MB/s eta 0:00:13
   ---- ----------------------------------- 5.2/44.5 MB 3.1 MB/s eta 0:00:13
   ----- ---------------------------------- 5.8/44.5 MB 3.1 MB/s eta 0:00:13
   ----- ---------------------------------- 6.6/44.5 MB 3.1 MB/s eta 0:00:13
   ------ --------------------------------- 7.3/44.5 MB 3.2 MB/s eta 0:00:12
   ------- -------------------------------- 8.1/44.5 MB 3.3 MB/s eta 0:00:12
   -------- ------------------------------- 8.9/44.5 MB 3.3 MB/s eta 0:00:11
   -------- ------------------------------- 9.7/44.5 MB 3.3 MB/s eta 0:00:11
   --------- ------------------------------ 10.5/44.5 MB 3.4 MB/s eta 0:00:11
   ---------- ----------------------------- 11.3/44.5 MB 3.4 MB/s eta 0:00:10
   ---------- ----------------------------- 12.1/44.5 MB 3.4 MB/s eta 0:00:10
   ----------- ---------------------------- 13.1/44.5 MB 3.5 MB/s eta 0:00:10
   ------------ --------------------------- 13.9/44.5 MB 3.5 MB/s eta 0:00:09
   ------------- -------------------------- 14.7/44.5 MB 3.5 MB/s eta 0:00:09
   -------------- ------------------------- 15.7/44.5 MB 3.6 MB/s eta 0:00:09
   -------------- ------------------------- 16.5/44.5 MB 3.6 MB/s eta 0:00:08
   --------------- ------------------------ 17.6/44.5 MB 3.7 MB/s eta 0:00:08
   ---------------- ----------------------- 18.4/44.5 MB 3.7 MB/s eta 0:00:08
   ---------------- ----------------------- 18.9/44.5 MB 3.7 MB/s eta 0:00:08
   ----------------- ---------------------- 19.7/44.5 MB 3.7 MB/s eta 0:00:07
   ------------------ --------------------- 20.4/44.5 MB 3.6 MB/s eta 0:00:07
   ------------------- -------------------- 21.2/44.5 MB 3.7 MB/s eta 0:00:07
   -------------------- ------------------- 22.3/44.5 MB 3.7 MB/s eta 0:00:07
   -------------------- ------------------- 23.1/44.5 MB 3.7 MB/s eta 0:00:06
   --------------------- ------------------ 23.9/44.5 MB 3.7 MB/s eta 0:00:06
   ---------------------- ----------------- 24.9/44.5 MB 3.8 MB/s eta 0:00:06
   ---------------------- ----------------- 25.4/44.5 MB 3.7 MB/s eta 0:00:06
   ----------------------- ---------------- 26.5/44.5 MB 3.8 MB/s eta 0:00:05
   ------------------------ --------------- 27.3/44.5 MB 3.8 MB/s eta 0:00:05
   ------------------------- -------------- 28.0/44.5 MB 3.8 MB/s eta 0:00:05
   ------------------------- -------------- 28.8/44.5 MB 3.8 MB/s eta 0:00:05
   -------------------------- ------------- 29.6/44.5 MB 3.8 MB/s eta 0:00:04
   --------------------------- ------------ 30.4/44.5 MB 3.8 MB/s eta 0:00:04
   ---------------------------- ----------- 31.2/44.5 MB 3.8 MB/s eta 0:00:04
   ---------------------------- ----------- 31.7/44.5 MB 3.8 MB/s eta 0:00:04
   ----------------------------- ---------- 32.5/44.5 MB 3.8 MB/s eta 0:00:04
   ----------------------------- ---------- 33.0/44.5 MB 3.7 MB/s eta 0:00:04
   ------------------------------ --------- 33.8/44.5 MB 3.7 MB/s eta 0:00:03
   ------------------------------- -------- 34.6/44.5 MB 3.7 MB/s eta 0:00:03
   ------------------------------- -------- 35.4/44.5 MB 3.7 MB/s eta 0:00:03
   -------------------------------- ------- 36.2/44.5 MB 3.7 MB/s eta 0:00:03
   --------------------------------- ------ 37.2/44.5 MB 3.7 MB/s eta 0:00:02
   ---------------------------------- ----- 38.3/44.5 MB 3.8 MB/s eta 0:00:02
   ----------------------------------- ---- 39.1/44.5 MB 3.8 MB/s eta 0:00:02
   ----------------------------------- ---- 39.8/44.5 MB 3.8 MB/s eta 0:00:02
   ------------------------------------ --- 40.9/44.5 MB 3.8 MB/s eta 0:00:01
   ------------------------------------- -- 41.7/44.5 MB 3.8 MB/s eta 0:00:01
   -------------------------------------- - 42.5/44.5 MB 3.8 MB/s eta 0:00:01
   ---------------------------------------  43.5/44.5 MB 3.8 MB/s eta 0:00:01
   ---------------------------------------  44.3/44.5 MB 3.8 MB/s eta 0:00:01
   ---------------------------------------- 44.5/44.5 MB 3.8 MB/s eta 0:00:00
Downloading threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
Successfully installed joblib-1.4.2 scikit-learn-1.5.2 scipy-1.14.1 threadpoolctl-3.5.0

In [43]:
from sklearn.feature_extraction.text import CountVectorizer

In [45]:
countv=CountVectorizer(max_features=10000, stop_words='english')

In [46]:
countv

CountVectorizer(max_features=10000, stop_words='english')

In [47]:

vector=countv.fit_transform(new_data['tags'].values.astype('U')).toarray()

In [48]:

vector.shape

(10000, 10000)

In [49]:
from sklearn.metrics.pairwise import cosine_similarity

In [50]:
similarity=cosine_similarity(vector)

In [51]:
similarity

array([[1.        , 0.05634362, 0.13041013, ..., 0.07559289, 0.11065667,
        0.06900656],
       [0.05634362, 1.        , 0.07715167, ..., 0.        , 0.03636965,
        0.        ],
       [0.13041013, 0.07715167, 1.        , ..., 0.02300219, 0.0673435 ,
        0.09449112],
       ...,
       [0.07559289, 0.        , 0.02300219, ..., 1.        , 0.03253   ,
        0.03042903],
       [0.11065667, 0.03636965, 0.0673435 , ..., 0.03253   , 1.        ,
        0.04454354],
       [0.06900656, 0.        , 0.09449112, ..., 0.03042903, 0.04454354,
        1.        ]])

In [52]:
new_data[new_data['title']=="The Godfather"].index[0]

np.int64(2)

In [53]:
distance = sorted(list(enumerate(similarity[2])), reverse=True, key=lambda vector:vector[1])
for i in distance[0:5]:
    print(new_data.iloc[i[0]].title)

The Godfather
The Godfather: Part II
Blood Ties
Joker
Bomb City

In [54]:
def recommand(movies):
    index=new_data[new_data['title']==movies].index[0]
    distance = sorted(list(enumerate(similarity[index])), reverse=True, key=lambda vector:vector[1])
    for i in distance[0:5]:
        print(new_data.iloc[i[0]].title)

In [55]:
recommand("Iron Man")

Iron Man
Iron Man 3
Guardians of the Galaxy Vol. 2
Avengers: Age of Ultron
Star Wars: Episode III - Revenge of the Sith

In [56]:
import pickle

In [57]:
pickle.dump(new_data, open('movies_list.pkl', 'wb'))

In [58]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))

In [59]:
pickle.load(open('movies_list.pkl', 'rb'))

,id,title,tags
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...
...,...,...,...
9995,10196,The Last Airbender,"The story follows the adventures of Aang, a yo..."
9996,331446,Sharknado 3: Oh Hell No!,The sharks take bite out of the East Coast whe...
9997,13995,Captain America,"During World War II, a brave, patriotic Americ..."
9998,2312,In the Name of the King: A Dungeon Siege Tale,A man named Farmer sets out to rescue his kidn...
9999,455957,Domino,Seeking justice for his partner’s murder by an...